# Generated by Django 4.0.5 on 2022-07-21 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, max_length=1080, verbose_name='Description')),
                ('type', models.CharField(max_length=255, verbose_name='Type')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('time_updated', models.DateTimeField(auto_now=True, verbose_name='Updated time')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, max_length=1080, verbose_name='Description')),
                ('tag', models.CharField(blank=True, max_length=255, verbose_name='Tag')),
                ('priority', models.PositiveSmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0, verbose_name='Priority')),
                ('status', models.CharField(choices=[('to_do', 'To do'), ('in_progress', 'In progress'), ('done', 'Done')], default='reader', max_length=255, verbose_name='Status')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('time_updated', models.DateTimeField(auto_now=True, verbose_name='Updated time')),
                ('assignee_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignee_user', to=settings.AUTH_USER_MODEL, verbose_name='Assignee User')),
                ('author_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_user', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.project', verbose_name='Project')),
            ],
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('reader', 'Reader'), ('editor', 'Editor')], default='reader', max_length=255, verbose_name='Permission')),
                ('role', models.CharField(blank=True, max_length=255, verbose_name='Role')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.project', verbose_name='Project')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=1080, verbose_name='Description')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('time_updated', models.DateTimeField(auto_now=True, verbose_name='Updated time')),
                ('author_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('issue_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.issue', verbose_name='Issue')),
            ],
        ),
    ]
