# Generated by Django 4.1 on 2022-08-19 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project_management", "0002_alter_issue_assignee_user_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="issue",
            old_name="assignee_user_id",
            new_name="assignee_user",
        ),
        migrations.RenameField(
            model_name="issue",
            old_name="author_user_id",
            new_name="author_user",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="author_user_id",
        ),
        migrations.RemoveField(
            model_name="contributor",
            name="project_id",
        ),
        migrations.RemoveField(
            model_name="contributor",
            name="user_id",
        ),
        migrations.RemoveField(
            model_name="issue",
            name="project_id",
        ),
        migrations.AddField(
            model_name="comment",
            name="author_user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Author",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contributor",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contributions",
                to="project_management.project",
                verbose_name="Project",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contributor",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contributions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="issue",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="issues",
                to="project_management.project",
                verbose_name="Project",
            ),
            preserve_default=False,
        ),
    ]
