# Generated by Django 4.1 on 2022-08-19 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "project_management",
            "0003_rename_assignee_user_id_issue_assignee_user_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="issue_id",
        ),
        migrations.AddField(
            model_name="comment",
            name="issue",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="project_management.issue",
                verbose_name="Issue",
            ),
            preserve_default=False,
        ),
    ]
