# Generated by Django 4.1 on 2022-08-28 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("project_management", "0004_remove_comment_issue_id_comment_issue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contributor",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contributors",
                to="project_management.project",
                verbose_name="Project",
            ),
        ),
    ]
